# Docker CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: /go/src/github.com/jainishshah17/tugger

    steps:
      - checkout
      - setup_remote_docker

      # Login to docker registry
      - run: docker login -u $USER -p $PASSWORD
      # Build docker image
      - run: docker build --rm=false -t jainishshah17/tugger:$CIRCLE_BUILD_NUM .
      - run: docker tag jainishshah17/tugger:$CIRCLE_BUILD_NUM jainishshah17/tugger:latest
      - run: docker push jainishshah17/tugger:$CIRCLE_BUILD_NUM
      - run: docker push jainishshah17/tugger:latest
