{{- if .Values.rules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tugger.fullname" . }}
  labels:
    app: {{ template "tugger.name" . }}
    chart: {{ template "tugger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  policy.yaml: |
    rules:
      {{- toYaml .Values.rules | nindent 6 }}
{{- end }}
